apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebd                     
  labels:
    app: mywebd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebd
  template:
    metadata:
      labels:
        app: mywebd
    spec:
      containers:
      - name: apache-webserver-php
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80        
